### ISSUE TITLE
Rely on OPCache optimizations for shared arrays for the list of domains

### ISSUE THREAD

**Issue by stof** [salaros/free-mailchecker#3]
Currently, the list of domains is built using a `array_unique` call. This prevents keeping the big array in shared memory in OPCache on PHP 7.

If the array could be already de-duplicated in the source code (or if duplicates could be considered a non-issue), the array would stay non-mutated, and so could be kept in shared memory by OPCache.

Is the filtering actually useful here ? Neither https://github.com/salaros/is-biz-mail-dotnet nor https://github.com/salaros/is-biz-mail-js have the equivalent filtering.

**Comment by salaros** [comment]
You are right, that's a relics from my initial implementation. Anyway currently make script still relies on [SpamAssasin's](https://svn.apache.org/repos/asf/spamassassin/trunk/rules/20_freemail_domains.cf) list of free domains, which can have some collision with locally defined in [not-found-in-spamassassin-list.txt](https://github.com/salaros/is-biz-mail-php/blob/master/assets/not-found-in-spamassassin-list.txt).
I have to filter those possible duplicates upon build and benefit from OPCache caching array definition

**Comment by salaros** [comment]
@stof thanks for your priceless contributions, please feel free to star this project if you think it's useful 😄
