### ISSUE TITLE
More domains from spamassassin

### ISSUE THREAD

**Issue by stof** [salaros/free-mailchecker#5]
The spamassassin  source code contains 2 files with a list of domains:

- https://github.com/apache/spamassassin/blob/trunk/rules/20_freemail_domains.cf which is used currently
- https://github.com/apache/spamassassin/blob/trunk/rules/20_freemail_mailcom_domains.cf which is not used currently

It may be worth checking whether the second file should also be used.

**Comment by salaros** [comment]
This was implemented some time ago, apparently I just forgot to mention the issue code inside the related commit message
